// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial02PM.Context;

namespace Parcial02PM.Migrations
{
    [DbContext(typeof(ClinicContext))]
    [Migration("20210525194436_InitialC")]
    partial class InitialC
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Parcial02PM.Entities.Questions.Question", b =>
                {
                    b.Property<int>("IdQ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Quest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQ");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Parcial02PM.Entities.Reservations.Reservation", b =>
                {
                    b.Property<int>("IdR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpecialityIdS")
                        .HasColumnType("int");

                    b.Property<int?>("UserCardId")
                        .HasColumnType("int");

                    b.HasKey("IdR");

                    b.HasIndex("SpecialityIdS");

                    b.HasIndex("UserCardId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Parcial02PM.Entities.Specialities.Speciality", b =>
                {
                    b.Property<int>("IdS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("S")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdS");

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("Parcial02PM.Entities.Users.User", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuestionIdQ")
                        .HasColumnType("int");

                    b.HasKey("CardId");

                    b.HasIndex("QuestionIdQ");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Parcial02PM.Entities.Reservations.Reservation", b =>
                {
                    b.HasOne("Parcial02PM.Entities.Specialities.Speciality", "Speciality")
                        .WithMany()
                        .HasForeignKey("SpecialityIdS");

                    b.HasOne("Parcial02PM.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserCardId");

                    b.Navigation("Speciality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Parcial02PM.Entities.Users.User", b =>
                {
                    b.HasOne("Parcial02PM.Entities.Questions.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionIdQ");

                    b.Navigation("Question");
                });
#pragma warning restore 612, 618
        }
    }
}
